[package]
name = "share_nft_token"
version = "1.0.0"
authors = ["jack the dev <joao@hackachain.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0"
near-contract-standards = "4.0.0"

[dev-dependencies]
rstest = "0.14.0"